---
version: "2"

tasks:
  lint:
    desc: "Quick syntax tests"
#   ignore because we use `build-base` apk package
    cmds:
      - docker run --rm -tv ${PWD}:/app hadolint/hadolint:v1.8.0
        hadolint --ignore=DL3018
        /app/alpine/Dockerfile
        /app/debian/Dockerfile

  build:
    desc: "Build current images as latest. Suitable while developing"
    deps: [lint]
    cmds:
      - docker build -f alpine/Dockerfile . --tag antonmarin/github-pages:latest-alpine
      - docker build -f debian/Dockerfile . --tag antonmarin/github-pages:latest

  test:
    desc: "Test building containers. Use `task test GEM_VERSION=123` to test GEM_VERSION"
    deps: [lint]
    cmds:
      - docker build -f alpine/Dockerfile . --build-arg GEM_VERSION={{ .GEM_VERSION }}
      - docker build -f debian/Dockerfile . --build-arg GEM_VERSION={{ .GEM_VERSION }}

  update:
    desc:
      "Use `task update GEM_VERSION=123` to test and update Dockerfile"
    cmds:
      - task: test
        vars:
          GEM_VERSION:
            sh: echo {{ .GEM_VERSION }}
      - docker run --rm -it -v $PWD:/app -w /app busybox sed
        -i"" "s/^ARG\ GEM_VERSION=.*/ARG\ GEM_VERSION={{ .GEM_VERSION }}/" */Dockerfile

  release:
    desc:
      "Use `task release GEM_VERSION=123` to release."
    cmds:
      - git tag {{ .GEM_VERSION }} && git push --follow-tags --tags